In [53]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

import random as rand

# This code creates a virtual display to draw game images on. 
# If you are running locally, just ignore it
import os
if type(os.environ.get("DISPLAY")) is not str or len(os.environ.get("DISPLAY"))==0:
    !bash ../xvfb start
    %env DISPLAY=:1

### OpenAI Gym

We're gonna spend several next weeks learning algorithms that solve decision processes. We are then in need of some interesting decision problems to test our algorithms.

That's where OpenAI gym comes into play. It's a python library that wraps many classical decision problems including robot control, videogames and board games.

So here's how it works:

In [81]:
import gym
env = gym.make("MountainCar-v0")
# plt.imshow(env.render('rgb_array'))
print("Observation space:", env.observation_space)
print("Action space:", env.action_space)

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Observation space: Box(2,)
Action space: Discrete(3)


Note: if you're running this on your local machine, you'll see a window pop up with the image above. Don't close it, just alt-tab away.

### Gym interface

The three main methods of an environment are
* __reset()__ - reset environment to initial state, _return first observation_
* __render()__ - show current environment state (a more colorful version :) )
* __step(a)__ - commit action __a__ and return (new observation, reward, is done, info)
 * _new observation_ - an observation right after commiting the action __a__
 * _reward_ - a number representing your reward for commiting action __a__
 * _is done_ - True if the MDP has just finished, False if still in progress
 * _info_ - some auxilary stuff about what just happened. Ignore it ~~for now~~.

In [14]:
obs0 = env.reset()
print("initial observation code:", obs0)

# Note: in MountainCar, observation is just two numbers: car position and velocity

initial observation code: [-0.59081396  0.        ]


In [15]:
print("taking action 2 (right)")
new_obs, reward, is_done, _ = env.step(2)

print("new observation code:", new_obs)
print("reward:", reward)
print("is game over?:", is_done)

# Note: as you can see, the car has moved to the riht slightly (around 0.0005)

taking action 2 (right)
new observation code: [-0.58931326  0.0015007 ]
reward: -1.0
is game over?: False


(array([-0.54068619,  0.00113637]), -1.0, False, {})

### Play with it

Below is the code that drives the car to the right. 

However, it doesn't reach the flag at the far right due to gravity. 

__Your task__ is to fix it. Find a strategy that reaches the flag. 

You're not required to build any sophisticated algorithms for now, feel free to hard-code :)

_Hint: your action at each step should depend either on __t__ or on __s__._

In [44]:

# create env manually to set time limit. Please don't change this.
TIME_LIMIT = 250
env = gym.wrappers.TimeLimit(gym.envs.classic_control.MountainCarEnv(),
                             max_episode_steps=TIME_LIMIT + 1)
s = env.reset()
actions = {'left': 0, 'stop': 1, 'right': 2}

# prepare "display"
%matplotlib notebook
fig = plt.figure()
ax = fig.add_subplot(111)
fig.show()

def policy(t):
    if t<50:
        return actions['left']
    if t<100:
        return actions['right']
    if t<150:
        return actions['left']
    return actions['right']


for t in range(TIME_LIMIT):
    
    s, r, done, _ = env.step(policy(t))
    
    #draw game image on display
    ax.clear()
    ax.imshow(env.render('rgb_array'))
    fig.canvas.draw()
    
    if done:
        print("Well done!")
        break
else:    
    print("Time limit exceeded. Try again.")

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.


In [55]:
def static_policy(t):
    if t<50:
        return actions['left']
    if t<100:
        return actions['right']
    if t<150:
        return actions['left']
    return actions['right']

def random_policy(t):
    choice = rand.choice(['left','right'])
    return actions[choice]


In [75]:
def game(env, policy):
    env.reset()
    for t in range(TIME_LIMIT):
        s, r, done, _ = env.step(policy(t))
        if done:
            return True
    return False
        
env = gym.wrappers.TimeLimit(gym.envs.classic_control.MountainCarEnv(), max_episode_steps=TIME_LIMIT + 1)

game(env, random_policy)



WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.


False

In [78]:
def run_cycle(cycle_len = 1000):
    env = gym.wrappers.TimeLimit(gym.envs.classic_control.MountainCarEnv(), max_episode_steps=TIME_LIMIT + 1)
    for i in range(cycle_len):
        if game(env, random_policy):
            print('Finished')
            
run_cycle()




WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.


### Submit to coursera

In [ ]:
from submit import submit_interface
submit_interface(policy, <EMAIL>, <TOKEN>)

In [115]:
import numpy as np
solution = np.array([125, 0.1, -0.3])
def f(w): return -np.sum((w - solution)**2)

npop = 100      # population size
sigma = 0.1    # noise standard deviation
alpha = 0.001  # learning rate
w = np.random.randn(3) # initial guess
for i in range(30):
    N = np.random.randn(npop, 3)
    R = np.zeros(npop)
    for j in range(npop):
        w_try = w + sigma*N[j]
        R[j] = f(w_try)
    A = (R - np.mean(R)) / np.std(R)
    w = w + alpha/(npop*sigma) * np.dot(N.T, A)

w

array([0.61527417, 0.085821  , 1.62472966])

In [111]:
m1 = np.ones((3,4))
m2 = np.random.randn(3,4)
print(m2.shape)
np.dot(m1.T,m2)

(3, 4)


array([[-5.05791681, -2.76025832,  1.24975011,  0.71110893],
       [-5.05791681, -2.76025832,  1.24975011,  0.71110893],
       [-5.05791681, -2.76025832,  1.24975011,  0.71110893],
       [-5.05791681, -2.76025832,  1.24975011,  0.71110893]])

In [110]:
??np.dot